# Generated by Django 5.2.4 on 2025-08-31 23:17
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        # This operation enables the pg_trgm extension on PostgreSQL.
        TrigramExtension(),
    ]
