# Generated by Django 5.2.4 on 2025-08-31 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_experience_company_alter_experience_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educations",
                to="users.profile",
            ),
        ),
    ]
