# Generated by Django 5.2.4 on 2025-09-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_profile_achievements_profile_dob_certificate_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="certificate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="project",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="achievements",
            field=models.TextField(blank=True, null=True),
        ),
    ]
