# Generated by Django 5.2.4 on 2025-09-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_profile_certificate_profile_project_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar_blob",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar_content_type",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar_filename",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar_size",
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
