# Generated by Django 5.2.4 on 2025-09-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_profile_avatar_blob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
