# Generated by Django 5.2.4 on 2025-09-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner_img_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
