
services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 p2p_comm.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_HOST=db
      - REDIS_HOST=redis
    networks:
      - p2p-network

  celery:
    build: .
    command: /app/entrypoint.sh celery -A p2p_comm worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_HOST=db
      - REDIS_HOST=redis
    networks:
      - p2p-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - p2p-network

volumes:
  postgres_data:

networks:
  p2p-network:
    driver: bridge